{
 "title": "Prove",
 "time": { "from": "2020-04-07T16:10:29.023Z", "to": "2020-04-07T16:26:44.966Z" },
 "panels": [
  {
   "title": "Richieste REST",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/prosegui\",}",
     "legendFormat": "{{job}} - status: {{status}}"
    }
   ]
  },
  {
   "title": "Fallimenti REST ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"400\"}",
     "legendFormat": "{{job}} - status: {{status}}"
    }
   ]
  },
  {
   "title": "Latency di /prosegui",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_server_requests_latency_sec_seconds_sum[1m])"
    }
   ]
  }
 ]
}