{
 "title": "Applicazioni",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "STATUS SERVIZIO A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"a-actuator\"}"
    }
   ]
  },
  {
   "title": "STATUS SERVIZIO B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"b-actuator\"}"
    }
   ]
  },
  {
   "title": "STATUS SERVIZIO C",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"c-actuator\"}"
    }
   ]
  },
  {
   "title": "STATUS GATEWAY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"gateway-actuator\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 5 },
   "targets": [
    { "expr": "process_cpu_usage*100", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Uptime A",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=\"a-actuator\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime B",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=\"b-actuator\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime C",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=\"c-actuator\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime Gateway",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=\"gateway-actuator\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "Endpoint Rest Prosegui",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Numero di richieste totali al secondo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri, job) (rate(http_server_requests_seconds_count{uri=\"/prosegui\"}[10s]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Numero di richieste fallite al secondo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/prosegui\", status=~\"[4|5].*\"}[10s])",
     "legendFormat": "{{job}} - status: {{status}}"
    }
   ]
  },
  {
   "title": "Latenza",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/prosegui\"}[10s])/rate(http_server_requests_seconds_count{uri=\"/prosegui\"}[10s])  ",
     "legendFormat": "{{job}} - status: {{status}}"
    }
   ]
  }
 ]
}
{
 "title": "Messaggi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latenza invio messaggi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(template_msg_seconds_sum{operation=\"notify\"}[10s])/rate(template_msg_seconds_count{operation=\"notify\"}[10s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latenza processamento messaggi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(template_msg_seconds_sum{operation=\"listen\"}[10s])/rate(template_msg_seconds_count{operation=\"listen\"}[10s])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "Template Service Operations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latenza operazioni Servizio A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"a-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"a-actuator\"}[10s]))"
    }
   ]
  },
  {
   "title": "Latenza operazioni Servizio B",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"b-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"b-actuator\"}[10s]))"
    }
   ]
  },
  {
   "title": "Latenza operazioni Servizio C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"c-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"c-actuator\"}[10s]))"
    }
   ]
  },
  {
   "title": "Latenza operazioni Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"gateway-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"gateway-actuator\"}[10s]))"
    }
   ]
  }
 ]
}