{
 "title": "Applicazioni",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "STATUS SERVIZIO A",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"a-actuator\"}"
    }
   ]
  },
  {
   "title": "STATUS SERVIZIO B",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"b-actuator\"}"
    }
   ]
  },
  {
   "title": "STATUS SERVIZIO C",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"c-actuator\"}"
    }
   ]
  },
  {
   "title": "STATUS GATEWAY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"gateway-actuator\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 5 },
   "targets": [
    { "expr": "process_cpu_usage*100", "legendFormat": "{{job}}" }
   ]
  }
 ]
}