{
 "title": "Endpoint Rest Prosegui",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Numero di richieste al secondo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) ( rate(http_server_requests_seconds_count{uri=\"/prosegui\"}[30s]) )"
    }
   ]
  },
  {
   "title": "Numero di richieste al secondo fallite al secondo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/prosegui\", status=~\"[4|5].*\"}[30s])",
     "legendFormat": "{{application}} - status: {{status}}"
    }
   ]
  },
  {
   "title": "Latenza",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/prosegui\"}[30s])/rate(http_server_requests_seconds_count{uri=\"/prosegui\"}[30s])  ",
     "legendFormat": "{{application}} - status: {{status}}"
    }
   ]
  }
 ]
}