{
 "title": "Template Service Operations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latenza operazioni Servizio A",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"a-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"a-actuator\"}[10s]))"
    }
   ]
  },
  {
   "title": "Latenza operazioni Servizio B",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"b-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"b-actuator\"}[10s]))"
    }
   ]
  },
  {
   "title": "Latenza operazioni Servizio C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"c-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"c-actuator\"}[10s]))"
    }
   ]
  },
  {
   "title": "Latenza operazioni Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(template_service_operations_seconds_sum{job=\"gateway-actuator\"}[10s]))/sum by (operation) (rate(template_service_operations_seconds_count{job=\"gateway-actuator\"}[10s]))"
    }
   ]
  }
 ]
}